#!/usr/bin/env python3
"""Validate an Environment Builder config file and generate automation files.

On success it writes:
  install_vars.yml - Ansible variables (which technologies + versions to install)
  verify.conf      - one line per technology, read by scripts/verify.sh
On failure it prints every problem found and exits with code 1.
"""
from __future__ import annotations

import argparse
import logging
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

log = logging.getLogger("validator")

DEFAULT_SUPPORTED = Path(__file__).resolve().parent / "supported.yml"
REQUIRED_SPEC_KEYS = {"versions", "default", "check", "expect"}
ALLOWED_ENTRY_KEYS = {"name", "version"}


class ConfigError(Exception):
    """Raised when a file cannot be read or parsed."""


@dataclass(frozen=True)
class Technology:
    name: str
    version: str


def load_yaml(path: Path) -> Any:
    if not path.is_file():
        raise ConfigError(f"File not found: {path}")
    try:
        with path.open(encoding="utf-8") as fh:
            return yaml.safe_load(fh)
    except yaml.YAMLError as exc:
        raise ConfigError(f"{path} is not valid YAML: {exc}") from exc


def load_supported(path: Path) -> dict[str, dict[str, Any]]:
    data = load_yaml(path)
    techs = data.get("technologies") if isinstance(data, dict) else None
    if not isinstance(techs, dict) or not techs:
        raise ConfigError(f"{path}: expected a 'technologies' mapping")
    for name, spec in techs.items():
        missing = REQUIRED_SPEC_KEYS - set(spec or {})
        if missing:
            raise ConfigError(f"{path}: '{name}' is missing {sorted(missing)}")
    return techs


def validate(config: Any, supported: dict[str, dict[str, Any]]) -> tuple[list[Technology], list[str]]:
    """Return (technologies, errors). Collects all errors instead of stopping at the first."""
    if not isinstance(config, dict) or "technologies" not in config:
        return [], ["The config must have a top-level 'technologies' list."]

    entries = config["technologies"]
    if not isinstance(entries, list) or not entries:
        return [], ["'technologies' must be a non-empty list."]

    supported_names = ", ".join(sorted(supported))
    errors: list[str] = []
    result: list[Technology] = []
    seen: set[str] = set()

    for idx, entry in enumerate(entries, start=1):
        where = f"technologies[{idx}]"

        if isinstance(entry, str):  # shorthand: "- docker"
            entry = {"name": entry}
        if not isinstance(entry, dict) or not entry.get("name"):
            errors.append(f"{where}: each entry needs a 'name' field.")
            continue

        name = str(entry["name"]).strip().lower()

        unknown_keys = set(entry) - ALLOWED_ENTRY_KEYS
        if unknown_keys:
            errors.append(f"{where} ({name}): unknown field(s) {sorted(unknown_keys)}. Allowed: name, version.")

        if name not in supported:
            errors.append(f"{where}: technology '{name}' is not supported. Supported: {supported_names}.")
            continue
        if name in seen:
            errors.append(f"{where}: '{name}' is listed more than once.")
            continue
        seen.add(name)

        spec = supported[name]
        raw_version = entry.get("version", spec["default"])
        valid_versions = ", ".join(spec["versions"])

        # YAML reads 3.10 as the float 3.1, so force users to quote decimals.
        if isinstance(raw_version, float):
            errors.append(
                f"{where} ({name}): version must be quoted, e.g. version: \"3.10\" "
                f"(unquoted decimals are read as numbers, so 3.10 becomes {raw_version}). Valid: {valid_versions}."
            )
            continue

        version = str(raw_version).strip()
        if version not in spec["versions"]:
            errors.append(f"{where} ({name}): version '{version}' is not valid. Valid: {valid_versions}.")
            continue

        result.append(Technology(name, version))

    return result, errors


def write_outputs(techs: list[Technology], supported: dict[str, dict[str, Any]], out_dir: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)

    install_vars = {"env_technologies": {t.name: {"version": t.version} for t in techs}}
    with (out_dir / "install_vars.yml").open("w", encoding="utf-8") as fh:
        fh.write("# Generated by validate.py - do not edit by hand\n")
        yaml.safe_dump(install_vars, fh, sort_keys=False)

    # Format: name|version|check command|expected text|service
    lines = []
    for t in techs:
        spec = supported[t.name]
        lines.append("|".join([
            t.name,
            t.version,
            spec["check"].format(version=t.version),
            spec["expect"].format(version=t.version),
            spec.get("service", ""),
        ]))
    (out_dir / "verify.conf").write_text("\n".join(lines) + "\n", encoding="utf-8")


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Validate an Environment Builder config file.")
    parser.add_argument("--config", "-c", type=Path, required=True, help="user config file (YAML)")
    parser.add_argument("--supported", type=Path, default=DEFAULT_SUPPORTED, help="supported technologies file")
    parser.add_argument("--out-dir", "-o", type=Path, default=Path("output"), help="where generated files go")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    logging.basicConfig(level=logging.INFO, format="[%(levelname)s] %(message)s")
    args = parse_args(argv)

    try:
        supported = load_supported(args.supported)
        config = load_yaml(args.config)
    except ConfigError as exc:
        log.error("%s", exc)
        return 1

    log.info("Validating %s", args.config)
    techs, errors = validate(config, supported)

    if errors:
        for err in errors:
            log.error("%s", err)
        log.error("Validation FAILED (%d error(s)). Nothing will be installed.", len(errors))
        return 1

    for t in techs:
        log.info("  OK  %-8s %s", t.name, t.version)

    write_outputs(techs, supported, args.out_dir)
    log.info("Validation passed. Generated %s and %s",
             args.out_dir / "install_vars.yml", args.out_dir / "verify.conf")
    return 0


if __name__ == "__main__":
    sys.exit(main())
