apiVersion: v1
kind: Service
metadata:
  name: env-builder-validator
spec:
  type: NodePort
  selector:
    app: env-builder-validator
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
