#!/usr/bin/env bash
# Post-install check: confirms every requested technology is installed and working.
# Usage: verify.sh <verify.conf>
# Each line of verify.conf (generated by validate.py): name|version|check|expect|service
set -uo pipefail

CONF="${1:-verify.conf}"

if [[ ! -r "$CONF" ]]; then
    echo "[ERROR] Cannot read $CONF" >&2
    exit 2
fi

GREEN=$'\e[32m'; RED=$'\e[31m'; RESET=$'\e[0m'
[[ -t 1 ]] || { GREEN=""; RED=""; RESET=""; }

passed=0
failed=0

printf '%-8s %-8s %-6s %s\n' "TECH" "VERSION" "STATUS" "DETAILS"
printf '%s\n' "------------------------------------------------------------"

while IFS='|' read -r name version check expect service; do
    [[ -z "$name" || "$name" == \#* ]] && continue

    # Commands come from validator/supported.yml, not from the user config.
    output="$(bash -c "$check" 2>&1 | head -n 1)"
    status="OK"
    details="$output"

    if [[ "$output" != *"$expect"* ]]; then
        status="FAIL"
        details="expected '$expect', got: ${output:-<no output>}"
    elif [[ -n "$service" ]] && ! systemctl is-active --quiet "$service" 2>/dev/null; then
        status="FAIL"
        details="service '$service' is not running"
    elif [[ -n "$service" ]]; then
        details="$output (service $service active)"
    fi

    if [[ "$status" == "OK" ]]; then
        passed=$((passed + 1))
        color="$GREEN"
    else
        failed=$((failed + 1))
        color="$RED"
    fi
    printf '%-8s %-8s %s%-6s%s %s\n' "$name" "$version" "$color" "$status" "$RESET" "$details"
done < "$CONF"

printf '%s\n' "------------------------------------------------------------"
echo "Result: $passed passed, $failed failed"

if (( passed + failed == 0 )); then
    echo "[ERROR] $CONF contains no technologies" >&2
    exit 2
fi
(( failed == 0 ))
